//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS
    {
        public int ID { get; set; }
        public string tieu_de { get; set; }
        public string tom_tat { get; set; }
        public string noi_dung { get; set; }
        public Nullable<System.DateTime> time_tao { get; set; }
        public Nullable<int> numberRead { get; set; }
        public string image { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> UsersID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
